@startuml

!define ENTITY_COLOR #232F3E
!define ENTITY_BG_COLOR #FFFFFF
!define ENTITY_BORDER_COLOR #FF9900
!define ENTITY_SYMBOL_COLOR ENTITY_COLOR

!define TECHN_FONT_SIZE 12

skinparam defaultTextAlignment center

skinparam wrapWidth 200
skinparam maxMessageSize 150
skinparam shadowing false

skinparam Arrow {
    Color #666666
    FontColor #666666
    FontSize 12
}

!definelong EntityColoring(stereo)
skinparam rectangle<<stereo>> {
    StereotypeFontSize 0
    BackgroundColor ENTITY_BG_COLOR
    BorderColor ENTITY_BORDER_COLOR
}
skinparam participant<<stereo>> {
    BackgroundColor ENTITY_BG_COLOR
    BorderColor ENTITY_BORDER_COLOR
}
!enddefinelong

!definelong Entity(e_alias, e_label, e_color, e_sprite, e_stereo)
rectangle "==e_label\n<color:e_color><$e_sprite></color>\n" <<e_stereo>> as e_alias
!enddefinelong

!definelong EntityWithNote(e_alias, e_label, e_note, e_color, e_sprite, e_stereo)
rectangle "==e_label\n<color:e_color><$e_sprite></color>\n//<size:TECHN_FONT_SIZE>[e_note]</size>//" <<e_stereo>> as e_alias
!enddefinelong

' START entity_name
sprite $modem [64x31/16z] {
tTN5eSGm301HcTdJVxMVSNcbMzujCE7O8hwZrBs8P0oo1A1NbGxupdQYvA5lcgWrDbHHgt2etZKd5xX-QNKfdtsHRnakzv3bH9pK_xsVNEzPuT-Q2YTzXLiz
DFVtGa_wjFcGuYLysFddGazwFtZ8z9yNUj9x7kPb0kRps-_V_lnDxxzzz-hlRvtqXkzVwmYzTVmrZV-RRfr_hFEVY6yBbTMyo2i
}


EntityColoring(modem)
!define modem(e_alias, e_label) Entity(e_alias, e_label, #232F3E, modem, modem)

!define modemWithNote(e_alias, e_label, e_note) EntityWithNote(e_alias, e_label, e_note, #232F3E, modem, modem)

' END entity_name

' START entity_name
sprite $router [64x64/16z] {
fPU7igim34HTmBZg_F_Vlid5JnCq45BsrfZiIhQQuouGKgwj2qXlDQVWFi5I10CfosVaQNbwyRx41i38yNanvW4WwOwT11ZRoNR3De2nldJzzLlM0VHuJHUG
TEUUN9r21fgxGGFosq_Ujn8wy5Q8Lw3x4-loPf95WMhMAeXtRy8FACTp1S9Z4-zf120zUmH4vu8mRWMMyFYrsvlmiiiDU2smv3vv6mnTtkPsWd1v3FwF2uWU
sFR_qLmy29JLPEw4dhp0j5GWEIEGoJQy4qcFd3BDwrPK84Dtvm9QFWFyDByw8m1majw7vNMckppC6m6moHm1Zga_a3sKoIJ7ZkriaNn8klZdlZS5ffQCKwR4
F1HrNx71XAL7ru-dCXWkcA9FAEA1Be-NlHjF_Ghnm2-3YQHqjBZNGph3ak4gLQkbMtX8RV8jOgfTTwHq0yY3SJjHb6uXLA6xErnEpqxJRNw3IeVyFR_yoCzq
-T5_eLtUG6xvdTOP5tHXk-CFQaMkw9h1lQPubJyPd8LjnHMWvyKx0qYsVbOTSKYmDJbACZqfUXF0qVS7Ifyl9mxyFz_7CO6XArrXwHE3iJU1GqdJbMvwhmd8
xdg4P9gVqcrFytPeX-c5ehCZsEQDLLNY1glTgSr9JWHMI7P-HSu5EYJRnmInyrCtQWKooJR2f87tWjWfIJzssdM-4HKGnAiKTIuoKrMP2YDGdyFMvujWkES2
OzzeEou_QC5mJmKUzXTpprbDoA_XUzYdyMhlZ-Fz--F91RIyVtyD0iLPr7VlpmkJRf21xRtFH_doIRrlsTTMejnzG4e3Hdmra8o2PTkjMyG1I3cHM8jWZ5yR
WPQYrtZ7r00OwQq0LIP6owKD9jhYtaMgmW5IZUbR-2NbKbkh9QVbEhN_0G
}


EntityColoring(router)
!define router(e_alias, e_label) Entity(e_alias, e_label, #232F3E, router, router)

!define routerWithNote(e_alias, e_label, e_note) EntityWithNote(e_alias, e_label, e_note, #232F3E, router, router)

' END entity_name

' START entity_name
sprite $server [64x64/16z] {
xTRPcjim20LWX6H00iFxlssLr9_rERkLthIT_sOco_5EZk0M5f9cgyU1hzQ42i8hIrtZhRKk3xCMDznzjMxj_yIHst4RREEJIWXF85Nps1Z1HlOZG_W0xcV9
q6MF2ormGj6uS0ICpZASbYswv16QO4hIY1vtc1PN1IQL-4tJvE7lLa4u9SiQcsfnvKe9Ff18FQvCeXD0Y_FFNoZ2bk_OxkPDMwl2BBKrlPj7O-X6lilgyH7N
3Dt83wbGMptkZ9Ch2OQHlvDkm72Nd_37yZ_v1jDQNBIlufrBWjEIU5nfTCO89o3R7fKasrXmWVTIOVM84HI0H3P6X9US7WRpmcF-ZMxkNsd7chI3Gx5wBG_l
Fv8qzTUZtuJmpVEJoq8izK2Obf9_vkSVp0V291phe0c9OrSBd5HgR4JYeb663sLgCP8oVafCgAJNmq_xSe4JZEjVnCReQXLUIaPCrmnYBWjBrJ749kNk_YLk
7X_mnkdf_STCLHytkAzQAIESw6_4d17_uVx-wM_zhhyrsJVzRG30y_tDS37Vtx2PxE_Xlh-tzNjNMzFx_hupqz-FvOMaDktCUyIqQrLeoN3l5m
}


EntityColoring(server)
!define server(e_alias, e_label) Entity(e_alias, e_label, #232F3E, server, server)

!define serverWithNote(e_alias, e_label, e_note) EntityWithNote(e_alias, e_label, e_note, #232F3E, server, server)

' END entity_name

' START entity_name
sprite $switch [64x64/16z] {
nTTNWkmW34JH4aw0aMh_gtrXSi1DspNX_X_dW01WhSxJULtnK79UpEq_3z9hFbrrCWpcPC6b2kcs3lXW0ylEmEM2DLYl-vrEvZDYCRmfaoTzvIPw-gHvifZc
6UlOysOjQPxSDB_RmBTkyQXZaQvV0GJl4mxyieqzCz3tgR4CVKiuyFcUSvc0lf-3ztZqlLK-LETk8x_nTWDVANXX_yhvzwz_mRZ3-ozwfAPvODaqFwvapLV6
edboJuf_96EVkpaVYbdy_hFQhtx_VSB0pztsHxv9rtzF47oiWE2huTXF8vzduD1Fhho_LaZ1hyh_0wbHyPcFHUisy4lmTj_iOKNpmEmK_nzPz4XDyy0gUjXo
sglpYpe_gVCRdAnsHLib_N5-PSkdQoGZ0J1fVbRdzxy
}


EntityColoring(switch)
!define switch(e_alias, e_label) Entity(e_alias, e_label, #232F3E, switch, switch)

!define switchWithNote(e_alias, e_label, e_note) EntityWithNote(e_alias, e_label, e_note, #232F3E, switch, switch)

' END entity_name


@enduml