@startuml

!define ENTITY_COLOR #232F3E
!define ENTITY_BG_COLOR #FFFFFF
!define ENTITY_BORDER_COLOR #FF9900
!define ENTITY_SYMBOL_COLOR ENTITY_COLOR

skinparam defaultTextAlignment center

skinparam wrapWidth 200
skinparam maxMessageSize 150
skinparam shadowing false

skinparam Arrow {
    Color #666666
    FontColor #666666
    FontSize 12
}

!definelong EntityColoring(stereo)
skinparam rectangle<<stereo>> {
    StereotypeFontSize 0
    BackgroundColor ENTITY_BG_COLOR
    BorderColor ENTITY_BORDER_COLOR
}
skinparam participant<<stereo>> {
    BackgroundColor ENTITY_BG_COLOR
    BorderColor ENTITY_BORDER_COLOR
}
!enddefinelong

!definelong Entity(e_alias, e_label, e_color, e_sprite, e_stereo)
rectangle "==e_label\n<color:e_color><$e_sprite></color>\n" <<e_stereo>> as e_alias
!enddefinelong

' START entity_name
sprite $modem [256x124/16z] {
vD27WS0W3CLG0KvF_FUVzZhbsWBuRI3nNTakpSkljV2_lBkcvtlcJtOhYAlmIpuLo9duhhX2UJ8ZKpX6jqYH1vX2Adnv5DB3fqD1xRmh6ZsxPIQLbyCroW2t
Eb-PtAR11PWwpqmlkxe2fnfF46l00UeA8HGrZgdP2U9GatTLJXH9pNgfEWZZL7K-gemm5bMtgqg4aLKzQeWZ1Uz7bR-sTvVPqOH058Q1DlpT_se_T-7az5IF
X7j_nvuaCrWr9R_yyiill_pZo2-__FBBBx_yyliStILPQxZe2tT3_zwvoiybNzaNCFE72XVwwTi51rzs_WZN-g5uPvYbOUTVEzVxuR3xrqzWvlS5xkAdBSua
UyVEVy2z_90CNWIXWfb_QLplDor8Y63czmdkwuSQRXloiVDldVlx8Tuqv9lvGuM7-EdhwI7VpX_XKNx8_iIGNx7phvr7-c4_KUHWvlSP7kK_DndOEdR-7Hxe
Fr6W4GgO-PV6K_ZVlYYAOETFy2n-AE4Ddzwmys-TP_B3uSRn6SpyeJ1AMY_9mIXj7V5tiFCVF6Mo7mpvTlwbyQJf--2joiZlCq-S6WPJD0l_tddknC5IvsP_
g3nTnfE10-pyaPT8yOEtglF-jVCgEVxUbHb7Vlt_w_rFuv_cFvh_QlsZzQ_sFxJ_fVrFxN_h_4FdNph_rFdtEFi4zG-gVr7za-hVLFyuoZP1_QlgdrN_FipE
PCy_wFcNry_iVldbbrz--UMNNtxvvPTVVlbr_sMOnx_yz3U-Pvl7l_CzPVBxZrFaHwQy_ths-yzTd_l-UvTcxdyGdGipzx_mphaoLV-JdL-IrVz6_O-SgqoP
whx5ToPCyx--9ywKlyUwq63g1f2kC5Noluga9iXWckCZaoJEtV_OZzP6HogDTvfMqb_zhpy2
}


EntityColoring(modem)
!define modem(e_alias, e_label) Entity(e_alias, e_label, #232F3E, modem, modem)

' END entity_name

' START entity_name
sprite $router [256x256/16z] {
xPtPUkGg38J53cRH-x_jkJjV9fLsqnPowEdvxsQ9uofBOZ5WkXdZGigb7BMstWSpy-YzrNgKabDmXlvMZ8kbTdvAhoMwlq_vu9SOjSI_8nXyRdoHcXozDGwq
Vu07gFq3FOYLbr83lG-XiW97U0_n1wjn-0yMlxy5eV44_SWfnk2TiyOG6METyo76b8_E4zHD7OYTpncj96_f5EjJQUEPWt53zUDK-l5Q4-PIFRzUV1_rlKHB
5x3nEBjge6tmdH_GIZ0am8Jo-DgUji3LHpSO3It0f4SML4k_ZZqUP6Ys2oqk3pAX6FfLJBwhbVOFVCxxbRqMTRoEZHaPWNu9rvYHwaWDNpSg0uKPEQnskTaa
2VnW91jInnH6XgDxoGoCT5lH7RyS0hRzSfyyeGFDqbr41XBTJ68Wq3qSMFKCtOx1soXq0wP3wBjTXXtDt53t1Q6ldWJ3aovP5lhwIP1kJVtkjXjx7ufkDtcZ
gzyFhQI4xO9aKoHy3qfB6ZY5OglqO9n6eYd4lbeEUEqW6vws8YWR41LYNpK70gqaASI-SWv4MaTMpYwL64rQyXrjYWS3589_MDeM1ocmFAoweOsnOtaH37g5
NtzqxXVBhxGzRQa15iPMsrFvAvOac07D_lwKTVMgQpzz_GXegwOxAhqDRSsiQ3xpqT76z1Nz87-MHuuRxGdMBISl_GFaCxTtwGWD8uuX2_8thmXEMWEFamXo
UvT4pDuY6_HuaB-t0TXpZPBaJo3_BGp8WdvW1uqWVoy3l3ll1hJBrWq3URMN0IRankm9C134Lugd0_aR6M3_No3wj0RQQuFe1Cve621U8DoUnd6dMSg9kBg7
0IxLgRKFxSBmrKBoYmtGtr4O280IO6YA1iclQ81yFVYvDl_oNKP8VdK3vFi1-bHJ5cOi7g1Asm3vVX0kK-4yNYn-XfOOO8NfNlafSQwSPNg6XUWN6n2x8DqR
Jt5cSNwb4r0XMgG6HEPhwLuwppBeZ34_X-bXr2Sr85wSXIyymPoiE1y03TG83OYGTXe6n4Mg0ZZrcW77pzOtKZR0qIbkDgexbCeh1c3aaR81BrofpINAcEue
eW5uFQThGAKdcBbEK8V_9J8WYgVWCq-HNkdKjid_93OWBkWTPddwpp_Q3bUK610XGTKCeEVuvyysm7-H610MlOPE_9H690e0b198Qa201bhFW4mdJ6UZWz6a
m800ZYWQu6c6yIGQZwjFgqrrq0L4MVgZZOKG0pUxr02hPq2dESu7zXcQqwK6119WneMvZnSL3eYdfGOKYVo-n5fp5Z8UokbQ0xgQV3ONkjFkfFePqZ30IENB
Iwiz2KTegbORu1Naltg_5Kt32kj9nO2i8F_LnZeyB1eDd5bjG9FBbxUiZ_g01Z9ZlG5AyiV5HJqG_lBT3N5v0UYokO-pLYwi3dyAV4gI1vJyikERRn3-MKi-
roNouU_SrHcrdmFNhWf-P8Ny0h_dyhB0y5ExsFNairiXdoYAechyr6-0RDAGpqak7tzNlZwVzbDLD7ho-P3Bnz_cwN82E2mAVTqC3JBayj40eii9aB6LBGlb
8rOg7tzZ4wnhRjZwXOLJr4YKJYgZ0LcIglWtHbC-5wbyD218jZLuI7zL-Tobyj40G_82q2JfN_W5Z40-a2u-iEDxtq6I_hRn2mIPV3IWYDhgyRr5D4lNfY55
9XyD2B9zJVRFrgklNPk8D95y95aYIG68V-P3MRms5P7AbuE2EwIdtjTE_0RoAVuPZz0_MxOs7Sc21KKQM-F-B0Uq3lTpGMW2-Ulue-275ygVV0MdWdn90VHV
ot_Lsflq1RU1V6fV6u1ZAZbNhU1E9rEpG5K_8A5yCqDt1V-v9Ayk7yVhxLiogE_Ww6TXSe_yRoLFqFjTZTUMZprWGVEdWDUMZmsW5pH_w_4WNxa1j76lursy
gdniQtqIZ7xK3AYtdU0Tyswd6tcGhza1I8VWrOyEljvuCaAkWkwFEleTeADzadwS0QWm-_5P-XjqVp-1y9D-Hn-3_savYQLDqPm1wp3y-GGiwl-ddpu0UEC_
_kc7-FyW_V_o_zFRly_k__ph__OFrzy-U_nNFtt-ezmu_rNTTYU3vdoV_iRiTjEVxfl_Re96Lc_--qifK9U_ZG5VYlvTxx_QJjsiBvq-UF-f9bzWWEBxJmC3
02Nv0WDK5u31uZnj-US6z1BjVTs_GTJrEq2uP-_y_uuZEWAKrhzKzGQmCU2UDyqrUVtcxo3A2WsWO56hvo-qx8tg7ILS_wWl_znf_aOlmMYkVnGqW1hogJCo
ZcXrcZ_P-cUv_FaDDQCcfz3ymVftVVc2RUGj-xNhtmNx7tJaa-4dD4b10C7Y_IykBjxEqFav7Gh2nVqlylrFaUDI-NJm7ED8ZeJxdwxiVyFRZIBvQEWBL2lP
_mRx7oz6Kreedoo_G9BjVvJlVxLm6-AjJ4DLFkv_3P82467nf5G-LPubojBVBzZ_NXWC4Cgdf2CVoula_0FusRnAFhaByYNd7r2-K01EJWuoqcsCAl8n_TE2
yqy2xcusVKA-l004yTuF9pl_1aShPOryoXhoyTe_vMiNzV3B4lda5UHZ-1_YywymLSiL-OYUV0VNW2ecUb9ZXNng2l8XNrUSVvSPaSkdh24Vpx-Jdt_OLEIJ
rvBluIgoyozrv9DHE4aKpx-K9u1R8n_fIWR0D9Ji_Dka99yAgnWG8FnbvnzN9VaKMCM02b4kE_zQ85yu1zA4LoqhpZ-tg-GZGyE0SjRANLW97WNonPEWLTAg
z5DpqegRx2GXyde3CeIuyFiN5pv9AKWjiG4C4Ixx_ebXrZE0bnkGuCw4txy9h6O0DgsXYWp0xz_8ltzKMD6017r-eG7nwK-55mEWiw81xhjygG43UhXdWhmm
HUK6W7o90VXmvT-_ywnc06QZs80-azpzbIOWiwe16UvNOa22no_-_cLZLGCyo1SOO22PdWP0aQQ_z60Lk5s10GSyVl6NWZqh6z11_cK3tFJiMPikWOcL3IXm
jvSDwDEg_BHJbPKD270B5mo0g7RNld-Ey3Iz14klOq3-HGCC3ihbNyjtF85i1MyFH383i9zkNkhLMq7worTmMy5PgRDF535ZgbWSAclJ4Ba1_SM9ZJZbr-17
27PmQ1XGNdvpL2VAfLLOcwgohS2_qaz2RUE1dAYmDbd307Fb4vJbkMU7mjfq3GFQfKx8UBh4i0ls9gWQO1-EKVl5oHT7Y17iJL4rm84ESEQ4QT-28Dsr343v
1k9ucdvULPsZFMWW_q53rWJl7oBjItiiFrsCVlnXjxy1U9TUzWWhkBUv0UwaXX_2DIZ3x6q0ohShLmimzwqDGFbcY9uU9b2dZMaWlwyeNnbYQ5VSIUvoMhCA
ezBRq5QzXUvmeNUWBejRCs0MTt_Ami9jONJvNaz_M9BX1IjEjXiHo9TYDaFxWhjl0ic93FcqBNQ0V3c98QCsnGtM6BTcXfpQ4WURWtKCyBGb0UGl8-bTMkiX
HLe6plTNGrk1csw3Rd0DHrlXXtQAUjuu1pBhLoZ7k-Q0QRS4f-qxvW36VhTgFk-O0rcsBK2qBQKv-cLS5soxaPlDnT0lOWuMXQGysNZ43Sunlx4auGx_PZS8
_Hj7vmSBaa0nzBdS5tQ_dWIHWKXtOHj_fuTRrNV-tIpC38n4Dv460_d-JXUI3QbZ2YFT_SeqEr8igMAFTHiCfBZ6Z5H7QlWgE0DHWJYOaHODAM3IZtwFGB-7
oVmZDIotkWfsLkWd978ij23KHx_4a82rPG0fdXRW3zdXf_huneyGBWnsgJ8W77lhnm1w8DCkRsRqSPLvdGS-L-QjrIEky3czbXITeHEiZ_beWyyfbhR4vC4J
Z5PBJZ5uPmsHiSw7cCjHsznF9qFx4XghqW9jZis3bHZPqZiGAYjmU7eVuc8BQg0tmwope4PwJrngB00w3k_fmT7v4lq0xM-AyRaEVe41UwVV7nDoxVoKNdCm
zDTYN4Wvb-EejVK-c4VlhTRZA3cdu6vN_Xy
}


EntityColoring(router)
!define router(e_alias, e_label) Entity(e_alias, e_label, #232F3E, router, router)

' END entity_name

' START entity_name
sprite $server [256x256/16z] {
xDO5ikCm30PWcMHRUF_JBdFYQLxRy7x3PGlg7zOMKYvOM-_48gfcvaDcfYh2r7khM78AS4OXOUiiQluMfiAzOOB3out4V4KcL3CSJiGkwXjIxXXXVwa-RFZQ
uv1W7qZg1w6zm7O2afWVZWbXWBMX-94P8wmbTV5Ja1RXpP3DJyK8uKqIcR_4J8MPYQZtrcf5B2Ndb68Cy4M8CQMS2sAjjRNUYOXPHCrUhK7SRTzDkMD9uHrX
ijJEpsP9AV2ygayTEy5ACZvJ2Ath7rw5QWwmaP0hYQvPWi2-a5ADi9DObsSm2h1OqMKPl2OuW5JPV07Di4JY9J6Z1ZYKiAW8dE21A8S_-bYi3uCv1u2n80_E
Nk3maEtP2h2F6HKuZKBcOmIpq8S4uNHGV0XXIeUDJt1Iu-GkavSE3jy3d5heWn94-5FpEHJX0Y8zt04Tn8KB60SwXfza41Sl9FAu09EdhC85DPk_22VhKU2Y
qF_HP_xv6rnOdzu2Djc9onadV8Ky6lrxB45Y_qq3t40m_uq6eV3In7-nFtVXDind9BYDuXF_-t-V_LUV9tSv_b2-uUxVCl-DzPla_p6yH_GTimONzBczyz1I
d8UXy97abhZa_P_sBwosSI3SC6Q8ZUxfM-UZMTZwh0IGJxl_Gtaxc2Bpq4i1WAVR_DOmrBypyVu_c3dFV_3CUVw7e-fEy9sqrKrq_hlT273-l_gnsVNy_pO_
sl_XX-rzKFeTVh1IgATx8P2sumFqE_oQC5h_5_RpXiiV1_XdxVy3-6Vi_zId7k2Vil-tAFmnVesVeVyRuv-q_n_cdy3_04GWW7yg_mVddzF_mladzlzmVZp-
1FudK8xZ_5FxlpZ__FvtVtuD3U3_0_nJtV-0yqzw_mVEFqsCt_YDt_YDt_YDt_YDt_YDt_YDt_YDt_YDt_YDt_YDt_YDt_YDt_YDFtmEVWJatmzKWDr7ukFk
x_mES9NPwQND9xxYOS1hIDFIqx91IJGfFPoLPwENTJkKx6QYTsKxd9fu3dXERNik9TBey1JhzfMKoEF2IoeuQRf_2O0R4TxTL__ZpU-_jEui2857OkUGTqky
c_mFxlvlWpm64dQ5jInx-n_kaG4VvDJiCGCJ47RuaVaF9Na-vmm-PFx3BZ--P9JbFAy4KVJzr4Zm_f_Be7ZqvfS2-vGhLj7BiVrFIXNNhr9m_CtWBYHSGAkH
djZ_vLGFkZbBt5MUUydGfJrPmU7y6ehbAKafeUutZWseLKW5Z_DhoAzV4PTMDNb4c9c87g8ICRE8MaDhBkrv_zjJd_CFYNtzRpMTQhcagXNLCor7wNl-mtuO
_tlntE7y2wYlpfSSvTNdVquNdhC5S841VZ3aufdyx-Ze7UU_ujEx_U_avRtdtrgKbFQju7c9Navs_iyklDx_rbhxpFqFua9CIE62K-SrHUKUgl-3nNaVGanf
MLVaJX_rlzSbfHY2TqvupluNkehr__ICyHk_yHk_yHk_yHk_yHk_yHk_yHk_yHk_yHk_yHk_yHk_yHk_yHi_VGu-t-9l_37uRGCUW0_2rpJtiVgxPfqJ6P_i
riBS-B5j3rBTlFI-Ra0ApqalPJxv6O_Fsu7KE1KynROTpUhcVEhnj4N6XvS5GGNSvr4TQ3Ht_-JgXsIdi1v2tRiV90SU2vxtnBNbplT_7bt_LlO70ZZVsV_G
4c74nm0trOhix_-uCgB-hIum983lyECBHawUnqBNvVmnFpxrk2p1qNl9oKLGIyp-oFudBxYSiGJXxoTd5vGSoSA7zt_zUjpC4NerDea_R1cj_idzxsVKvvel
YXBrnhx8LVK92Tg1-zzm1OdFn5Vtc-afP5O7F2lsyTJaEfn_SCpzdEzIIlxJR_hJZygbb7ukU8xSx_n7mbgtOLBN8FtFlyYbV7xsdDmhp_yabR7iTvmV3clH
SQAK9JhkT_wBtxtpzbIi5CVvZvTXkRu9F3W-oVa_TN6_yKfJw8Jz3-h0vz9EvBxZ_5t3eXPyhUrPu5QBck_2m_U_436BY5Py8LubXE2zSqxlIRB-do_4-8tV
-8tV-8tV-8tV-8tV-8tV-8tV-8tV-8tV-8tV-8tV-8tV-8tV-Cldu9URAaZvGFoQjjyfz0dqLFv0ZhJzaIPp8E83mEbg77gS7JzT3xodgwOJFpDzQ7_3qetx
48hCIY_r2lN7SnqdrhztfPwWlnEtwzJm0HS_nD-_UQFvBD4yy9GspVMph_7jflGw1tp8Z--wuR8ZZStY_k-MUijTzPacUkOr2LWTVgSc6GzUqdqU0Qg3KUrl
DS2Vk-8e8VRts0Pu15OAOAxecEFFMmGgXJhIx6zy1ZX-gOyiyD394mGTnNdaCXkA5PU_wMtak09UGz-hO_gRASSdJNQynwYF-zpgPImdlmxRnyEoMKlIgOh0
qygF1u8wgUywzFruIfAkLUJpCz1Z3ByL7vLyw6hakJZdBt9GY1SZF9SAGR--SfUujcsWjBL_cK8-bH7OI_BqmcyLPR3nv_qZ0H2Vts43onaApluvRpckslFR
mDSKJb63q_SEWczbYLvE00xLfVqDyDE7Euv0Ru02VkAez-sy3_7tDJ-rtNJTzMAW6Bo_YE3Vy1B_5m
}


EntityColoring(server)
!define server(e_alias, e_label) Entity(e_alias, e_label, #232F3E, server, server)

' END entity_name

' START entity_name
sprite $switch [256x256/16z] {
xTnNUlCm3aPXaA94cY9vzh_QwNWyyU-KAMdwy5xcxhYf8R2dqj7wEHQNiCRPsv7ietARND1isTwNwkIonhkVWcDoQNEtDwJEvTtiLMKXO6xsNCSfVWJIHCP8
qlamapsOI1dsqic3SMmvsIMalDN1Wsx_hl72giak9jN52ytkoaEzNTB3Ar3CfOUZmsLrk5lfwPyFkx3wx8qkSBVPXJrl7Ghvhd1t_l6NtIwlFhxR0rmp0Vtb
1o23coPXWKjcJURJxmvmXzd0JHEnSASPkCD4LDoo0YwPY0mkLzmm6HDtT5mr6GtN1gwOZ1rtBjncCWfkB5mo6HatmDdlKxBzLn9k_kh-HhF_2cxzydvMqUw7
dhJxuH3lPsJjVhY9zxDsxNuuitO_LF5-vgRT3prfzxCExNuOMRiVcdW_gsZtmvcq-w6AzpEtdz8_FilYJRVqC_hvBclNxeUHjVkXYVUpYdO_zAJT3uTuFxTu
_rry_-FtFux_SVuNv_zn_HVN_t7_9-x_nVtVkFyVpt_Y-T-7nVFVUFxVYlByHraKtVcVr84YE_zry7T5TFvlctY_ulpd3RnVSFvtNxYYD_-TJ-wAtFn_nNc_
qlz_R9EVrb-oVLL_wl3Z-jtdznyBuVuyGBY_WN1_MGZtfnE4-oi8zsyJuVvq0-7-VV5DVa9_7Y3Stq2uloo4-rC7uVu3XFktYNJ_YNQ_bQNQxvful-MXsk-E
fTrlgQlskssgzhlActhxB3-at_AfUltlzgNQxsxY_RPDrNvtYFTRwghzhYpLVjV4-oqFrNwtB-r-IpVLVhTDrNvNnVijdQhzhYpLVjV4-oqFrNvtB9dvp-TI
YltltotslyV-zzZ_7llVO_zxx7-F_U-n_ptslyV-zzZ_7llVnVjZ_tliVu_zxx7_FVQ_n_xtsFykta_iVu_zxx7_NRS_tl_O_wxR7_lVTVjZ_tjS_wlsn_vt
uVxO_oxS7_lVXVjZ__jdzSVyHyp_nFnNpF_5_6VC_yRyTyp_bwpy_n-fe_p_FuVq_x_bWN9_0-7-VI7SdquGxgyWtBzDXFlJ3OJxZuLmVnuWtDz0kByiXFjJ
1-7-2iBzsqIv_mR2_Vj2k3-Vl6cEp_8Z-flq_kjj8ToVEWZt7o3SdmVA_GsK-oTI_V7-n_S_Vl_Z-1_dVt7-7zT_SVqVzt_Y_b_S_utx__7y9vx_nVFVUFuV
ynyn_nFpNp7_5_EVCVyRyzyn_-zIL-rtPRDVA-7cmcMJiJthtqn6mOs1sqt6WJixhfcC6wvLt30P2tSKSCb4P73Pm1qcekAMsS1DlO__QLRbFW0LN7tnPLYc
876NpEm4Tvg00QxxoP3GEK3dBZ--81n2Ntx_k6zmL-tI6jpb9ny9kbtO-NGdU5fmDv9TL9fmjnwl1zsgb_xgk-tFhuLRDTl5R7MzjIpkvC7gTT_i2jAsrxvu
qEsbYPJnvBT1o4oc_0ACP4zqHDpikR8GyCQIrDHLttotBovj5dl7FhYiiTi7v3QveDcoVLGwsgsFkRY0DSz-Qtkof_uA
}


EntityColoring(switch)
!define switch(e_alias, e_label) Entity(e_alias, e_label, #232F3E, switch, switch)

' END entity_name


@enduml